FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt fastapi

COPY app.py .
COPY database_sqlite.py .
COPY lufth_track_data.db .

RUN chmod +x app.py
RUN chmod +x database_sqlite.py
RUN chmod +x lufth_track_data.db
CMD ["python", "app.py"]