FROM neo4j:4.4

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip install pymongo

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY script_neo.py /app/script_neo.py

# EXPOSE 7687

# CMD ["python3", "/app/script_neo.py"]