FROM python:3.9

WORKDIR /app

# Installer les dépendances
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste de l'application
COPY . .

EXPOSE 5000

CMD ["python", "app.py"]